### PR TITLE
🐛 Fix XML docs not being found in working directory

### LINKED ISSUE #50: Possible bug when locating XML file
I may have found a bug by chance while looking through the source. I think the path constructed below should be checked with `DynamicApis.FileExists(path)` before returning it.

https://github.com/RicoSuter/Namotion.Reflection/blob/486001ebe8d488fb145c9bd71af0f7457c412dae/src/Namotion.Reflection/XmlDocsExtensions.cs#L709

But maybe I'm misunderstanding something. In that case this issue can be closed.

### PR DESCRIPTION
**Pull request by bert2**
Fixes  #50.

The test is a bit hacky, since it has to create a working directory that's different from the app domain's base directory and navigate into it.

### CODE REVIEW

File: src/Namotion.Reflection/XmlDocsExtensions.cs [hunk 1]
```diff
@@ -707,11 +707,15 @@ internal static string GetMemberElementName(dynamic member)
                     {
                         path = DynamicApis.PathCombine(baseDirectory, assemblyName.Name + ".xml");
                         if (DynamicApis.FileExists(path))
+                        {
+                            return path;
+                        }
+
+                        path = DynamicApis.PathCombine(baseDirectory, "bin\\" + assemblyName.Name + ".xml");
```
Comment (RicoSuter) [inline src/Namotion.Reflection/XmlDocsExtensions.cs:714]: We should use bin/ instead of bin\ to also support Unix systems...

Comment (bert2) [reply src/Namotion.Reflection/XmlDocsExtensions.cs]: You true. Fixed that.

**Comment by RicoSuter** [comment]
Lgtm, thanks for the PR.
